name: Release
on:
  push:
    tags:
      - "v*"
    branches:
      - "main"

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=Release
          -DCPACK_WIX_UPGRADE_GUID=${{ vars.PACKAGE_GUID }}

      - name: Build
        run: cmake --build build --config Release

      - name: Prepare Tools ( Linux )
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install rpm gnupg -y

      - name: Prepare Tools ( Windows )
        if: runner.os == 'Windows'
        run: |
          choco install openssl nsis -y
          dotnet tool install --global wix --version 4.0.4
          wix extension add --global WixToolset.UI.wixext/4.0.4

      - name: Install Windows SDK ( Windows )
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Package
        working-directory: build
        run: cpack -C Release

      - name: Package for Arch ( Linux )
        if: runner.os == 'Linux'
        working-directory: .github/pkg/arch
        run: |
          docker build -f Dockerfile -t arch-builder .
          docker run --rm -i \
            -v "$GITHUB_WORKSPACE/build/PKGBUILD:/opt/work/PKGBUILD:ro" \
            -v "$GITHUB_WORKSPACE/out/install:/opt/work/install:ro" \
            -v "$GITHUB_WORKSPACE/out/dist:/opt/dist" \
            -v "./pkg.sh:/home/builder/pkg.sh:ro" \
            arch-builder \
            bash pkg.sh

      - name: Prepare to Sign ( Linux )
        if: runner.os == 'Linux'
        run: echo "${{ secrets.GPG_KEY }}" | gpg --import

      - name: Prepare to Sign ( Windows )
        if: runner.os == 'Windows'
        working-directory: out/dist
        shell: pwsh
        run: |
          Set-Content -Path codesign.key -Value "${{ secrets.CODE_SIGN_KEY }}"
          Set-Content -Path codesign.crt -Value "${{ secrets.CODE_SIGN_CRT }}"
          Set-Content -Path intermediate.crt -Value "${{ secrets.INTERMEDIATE_CRT }}"
          openssl pkcs12 -export -inkey codesign.key `
            -in codesign.crt `
            -certfile intermediate.crt `
            -out codesign.pfx `
            -passout pass:${{ secrets.PASS }}

      - name: Sign Software ( Linux )
        if: runner.os == 'Linux'
        working-directory: out/dist
        run: |
          KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | awk '/sec/{print $2}' | cut -d'/' -f2)
          rpm --addsign --define "_gpg_name $KEY_ID" *.rpm

      - name: Sign Software ( Windows )
        if: runner.os == 'Windows'
        working-directory: out/dist
        shell: pwsh
        run: |
          signtool sign /f codesign.pfx `
            /p ${{ secrets.PASS }} `
            /fd SHA256 `
            /tr http://timestamp.digicert.com `
            /td SHA256 *.msi
          signtool sign /f codesign.pfx `
            /p ${{ secrets.PASS }} `
            /fd SHA256 `
            /tr http://timestamp.digicert.com `
            /td SHA256 *.exe
          Remove-Item codesign*

      - name: Info Output
        run: find out/dist -type f
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-${{ runner.os }}
          path: out/dist/*
          compression-level: '0'

  upload:
    if: false
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist

      - name: Create GitHub Release
        run: echo "TODO"